spring:
  # redis 缓存配置
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 5
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 10000ms

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    check-template-location: true

  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**


